name: Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Build_and_Deploy:
    runs-on: ubuntu-latest
    environment: STAGING
    steps:
      - uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_ENV: .env.template
          file_name: .env.dev
      - name: Generate environment file
        run: |
          env
          envsubst  < .env.template > .env.staging
          pwd
          ls -la
          cat .env.staging
          echo ".env.dev"
          cat .env.dev
